/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as ProfileRouteImport } from './routes/profile'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HistoryRouteImport } from './routes/history'
import { Route as GroupSessionRouteImport } from './routes/group-session'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as AiSessionRouteImport } from './routes/ai-session'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ReportSessionIdRouteImport } from './routes/report.$sessionId'
import { Route as GroupSessionSessionIdRouteImport } from './routes/group-session_.$sessionId'
import { Route as GdSessionIdRouteImport } from './routes/gd.$sessionId'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminSystemRouteImport } from './routes/admin/system'
import { Route as AdminSessionsRouteImport } from './routes/admin/sessions'
import { Route as AdminRolesRouteImport } from './routes/admin/roles'
import { Route as AdminPlansRouteImport } from './routes/admin/plans'
import { Route as AdminNotificationsRouteImport } from './routes/admin/notifications'
import { Route as AdminLoginRouteImport } from './routes/admin/login'
import { Route as AdminDashboardRouteImport } from './routes/admin/dashboard'
import { Route as AdminAuditRouteImport } from './routes/admin/audit'
import { Route as AdminAnalyticsRouteImport } from './routes/admin/analytics'
import { Route as AdminAdminsRouteImport } from './routes/admin/admins'
import { Route as AdminLayoutRouteImport } from './routes/admin/_layout'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryRoute = HistoryRouteImport.update({
  id: '/history',
  path: '/history',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupSessionRoute = GroupSessionRouteImport.update({
  id: '/group-session',
  path: '/group-session',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AiSessionRoute = AiSessionRouteImport.update({
  id: '/ai-session',
  path: '/ai-session',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ReportSessionIdRoute = ReportSessionIdRouteImport.update({
  id: '/report/$sessionId',
  path: '/report/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const GroupSessionSessionIdRoute = GroupSessionSessionIdRouteImport.update({
  id: '/group-session_/$sessionId',
  path: '/group-session/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const GdSessionIdRoute = GdSessionIdRouteImport.update({
  id: '/gd/$sessionId',
  path: '/gd/$sessionId',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSystemRoute = AdminSystemRouteImport.update({
  id: '/admin/system',
  path: '/admin/system',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminSessionsRoute = AdminSessionsRouteImport.update({
  id: '/admin/sessions',
  path: '/admin/sessions',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRolesRoute = AdminRolesRouteImport.update({
  id: '/admin/roles',
  path: '/admin/roles',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminPlansRoute = AdminPlansRouteImport.update({
  id: '/admin/plans',
  path: '/admin/plans',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminNotificationsRoute = AdminNotificationsRouteImport.update({
  id: '/admin/notifications',
  path: '/admin/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/admin/dashboard',
  path: '/admin/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAuditRoute = AdminAuditRouteImport.update({
  id: '/admin/audit',
  path: '/admin/audit',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/admin/analytics',
  path: '/admin/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminAdminsRoute = AdminAdminsRouteImport.update({
  id: '/admin/admins',
  path: '/admin/admins',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLayoutRoute = AdminLayoutRouteImport.update({
  id: '/admin/_layout',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ai-session': typeof AiSessionRoute
  '/dashboard': typeof DashboardRoute
  '/group-session': typeof GroupSessionRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AdminLayoutRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/gd/$sessionId': typeof GdSessionIdRoute
  '/group-session/$sessionId': typeof GroupSessionSessionIdRoute
  '/report/$sessionId': typeof ReportSessionIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ai-session': typeof AiSessionRoute
  '/dashboard': typeof DashboardRoute
  '/group-session': typeof GroupSessionRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin': typeof AdminLayoutRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/gd/$sessionId': typeof GdSessionIdRoute
  '/group-session/$sessionId': typeof GroupSessionSessionIdRoute
  '/report/$sessionId': typeof ReportSessionIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ai-session': typeof AiSessionRoute
  '/dashboard': typeof DashboardRoute
  '/group-session': typeof GroupSessionRoute
  '/history': typeof HistoryRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/register': typeof RegisterRoute
  '/admin/_layout': typeof AdminLayoutRoute
  '/admin/admins': typeof AdminAdminsRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/audit': typeof AdminAuditRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/login': typeof AdminLoginRoute
  '/admin/notifications': typeof AdminNotificationsRoute
  '/admin/plans': typeof AdminPlansRoute
  '/admin/roles': typeof AdminRolesRoute
  '/admin/sessions': typeof AdminSessionsRoute
  '/admin/system': typeof AdminSystemRoute
  '/admin/users': typeof AdminUsersRoute
  '/gd/$sessionId': typeof GdSessionIdRoute
  '/group-session_/$sessionId': typeof GroupSessionSessionIdRoute
  '/report/$sessionId': typeof ReportSessionIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ai-session'
    | '/dashboard'
    | '/group-session'
    | '/history'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/plans'
    | '/admin/roles'
    | '/admin/sessions'
    | '/admin/system'
    | '/admin/users'
    | '/gd/$sessionId'
    | '/group-session/$sessionId'
    | '/report/$sessionId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ai-session'
    | '/dashboard'
    | '/group-session'
    | '/history'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/plans'
    | '/admin/roles'
    | '/admin/sessions'
    | '/admin/system'
    | '/admin/users'
    | '/gd/$sessionId'
    | '/group-session/$sessionId'
    | '/report/$sessionId'
  id:
    | '__root__'
    | '/'
    | '/ai-session'
    | '/dashboard'
    | '/group-session'
    | '/history'
    | '/login'
    | '/profile'
    | '/register'
    | '/admin/_layout'
    | '/admin/admins'
    | '/admin/analytics'
    | '/admin/audit'
    | '/admin/dashboard'
    | '/admin/login'
    | '/admin/notifications'
    | '/admin/plans'
    | '/admin/roles'
    | '/admin/sessions'
    | '/admin/system'
    | '/admin/users'
    | '/gd/$sessionId'
    | '/group-session_/$sessionId'
    | '/report/$sessionId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AiSessionRoute: typeof AiSessionRoute
  DashboardRoute: typeof DashboardRoute
  GroupSessionRoute: typeof GroupSessionRoute
  HistoryRoute: typeof HistoryRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  RegisterRoute: typeof RegisterRoute
  AdminLayoutRoute: typeof AdminLayoutRoute
  AdminAdminsRoute: typeof AdminAdminsRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminAuditRoute: typeof AdminAuditRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminLoginRoute: typeof AdminLoginRoute
  AdminNotificationsRoute: typeof AdminNotificationsRoute
  AdminPlansRoute: typeof AdminPlansRoute
  AdminRolesRoute: typeof AdminRolesRoute
  AdminSessionsRoute: typeof AdminSessionsRoute
  AdminSystemRoute: typeof AdminSystemRoute
  AdminUsersRoute: typeof AdminUsersRoute
  GdSessionIdRoute: typeof GdSessionIdRoute
  GroupSessionSessionIdRoute: typeof GroupSessionSessionIdRoute
  ReportSessionIdRoute: typeof ReportSessionIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history': {
      id: '/history'
      path: '/history'
      fullPath: '/history'
      preLoaderRoute: typeof HistoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-session': {
      id: '/group-session'
      path: '/group-session'
      fullPath: '/group-session'
      preLoaderRoute: typeof GroupSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ai-session': {
      id: '/ai-session'
      path: '/ai-session'
      fullPath: '/ai-session'
      preLoaderRoute: typeof AiSessionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/report/$sessionId': {
      id: '/report/$sessionId'
      path: '/report/$sessionId'
      fullPath: '/report/$sessionId'
      preLoaderRoute: typeof ReportSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/group-session_/$sessionId': {
      id: '/group-session_/$sessionId'
      path: '/group-session/$sessionId'
      fullPath: '/group-session/$sessionId'
      preLoaderRoute: typeof GroupSessionSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gd/$sessionId': {
      id: '/gd/$sessionId'
      path: '/gd/$sessionId'
      fullPath: '/gd/$sessionId'
      preLoaderRoute: typeof GdSessionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/system': {
      id: '/admin/system'
      path: '/admin/system'
      fullPath: '/admin/system'
      preLoaderRoute: typeof AdminSystemRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/sessions': {
      id: '/admin/sessions'
      path: '/admin/sessions'
      fullPath: '/admin/sessions'
      preLoaderRoute: typeof AdminSessionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/roles': {
      id: '/admin/roles'
      path: '/admin/roles'
      fullPath: '/admin/roles'
      preLoaderRoute: typeof AdminRolesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/plans': {
      id: '/admin/plans'
      path: '/admin/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AdminPlansRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/notifications': {
      id: '/admin/notifications'
      path: '/admin/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AdminNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/audit': {
      id: '/admin/audit'
      path: '/admin/audit'
      fullPath: '/admin/audit'
      preLoaderRoute: typeof AdminAuditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/admin/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/admins': {
      id: '/admin/admins'
      path: '/admin/admins'
      fullPath: '/admin/admins'
      preLoaderRoute: typeof AdminAdminsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/_layout': {
      id: '/admin/_layout'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminLayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AiSessionRoute: AiSessionRoute,
  DashboardRoute: DashboardRoute,
  GroupSessionRoute: GroupSessionRoute,
  HistoryRoute: HistoryRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  RegisterRoute: RegisterRoute,
  AdminLayoutRoute: AdminLayoutRoute,
  AdminAdminsRoute: AdminAdminsRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminAuditRoute: AdminAuditRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminLoginRoute: AdminLoginRoute,
  AdminNotificationsRoute: AdminNotificationsRoute,
  AdminPlansRoute: AdminPlansRoute,
  AdminRolesRoute: AdminRolesRoute,
  AdminSessionsRoute: AdminSessionsRoute,
  AdminSystemRoute: AdminSystemRoute,
  AdminUsersRoute: AdminUsersRoute,
  GdSessionIdRoute: GdSessionIdRoute,
  GroupSessionSessionIdRoute: GroupSessionSessionIdRoute,
  ReportSessionIdRoute: ReportSessionIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
